TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'ObisConcept.NeosGallery': TRUE

    userInterface:
      translation:
        autoInclude:
          'ObisConcept.NeosGallery': ['NodeTypes/*']
