
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          ObisConcept.NeosGallery:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        ObisConcept.NeosGallery: true
